import type { Exercise, Position } from '../types/exercise';

/**
 * Professional pre-loaded exercise catalog
 * ~60 exercises covering S&C, Speed, COD, Mobility, Technique
 */
export const globalCatalog: Exercise[] = [
  // Strength Exercises
  {
    id: 'ex-001',
    name: 'Barbell Back Squat',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
  },
  {
    id: 'ex-002',
    name: 'Bench Press',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['OL', 'DL', 'LB', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
  },
  {
    id: 'ex-003',
    name: 'Deadlift',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
  },
  {
    id: 'ex-004',
    name: 'Overhead Press',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
  },
  {
    id: 'ex-005',
    name: 'Romanian Deadlift',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
  },
  {
    id: 'ex-006',
    name: 'Front Squat',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=uYumuL_G_V0',
  },
  {
    id: 'ex-007',
    name: 'Pull-ups',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
  },
  {
    id: 'ex-008',
    name: 'Dumbbell Rows',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=pYcpY20QaE8',
  },
  {
    id: 'ex-009',
    name: 'Lunges',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
  },
  {
    id: 'ex-010',
    name: 'Bulgarian Split Squat',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  },
  {
    id: 'ex-011',
    name: 'Hex Bar Deadlift',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL'],
    youtubeUrl: 'https://www.youtube.com/watch?v=tvrJOK1tS8w',
  },
  {
    id: 'ex-012',
    name: 'Incline Bench Press',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['OL', 'DL', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=SrqOu55lrYU',
  },
  {
    id: 'ex-061',
    name: 'Barbell Row',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
  },
  {
    id: 'ex-062',
    name: 'Trap Bar Deadlift',
    category: 'Strength',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL'],
    youtubeUrl: 'https://www.youtube.com/watch?v=tvrJOK1tS8w',
  },
  {
    id: 'ex-063',
    name: 'Plank Hold',
    category: 'Strength',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
  },

  // Speed Exercises
  {
    id: 'ex-013',
    name: '40-Yard Dash',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=YN_vplKfKDY',
  },
  {
    id: 'ex-014',
    name: '10-Yard Sprint',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=Fhwx41k7YYg',
  },
  {
    id: 'ex-015',
    name: 'Flying 20s',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=kJiRwKTqOD0',
  },
  {
    id: 'ex-016',
    name: 'Hill Sprints',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=gZNhSMdG-Mo',
  },
  {
    id: 'ex-017',
    name: 'Resisted Sprints (Sled)',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'LB', 'OL', 'DL'],
    youtubeUrl: 'https://www.youtube.com/watch?v=SfJJNb3PYYg',
  },
  {
    id: 'ex-018',
    name: 'Acceleration Starts',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=mKdZe5wPnAM',
  },
  {
    id: 'ex-019',
    name: 'Speed Endurance Runs',
    category: 'Speed',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=6XcDHIL_3Hw',
  },
  {
    id: 'ex-020',
    name: 'Tempo Runs',
    category: 'Speed',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=d8RZM23lYmQ',
  },

  // COD (Change of Direction)
  {
    id: 'ex-021',
    name: '5-10-5 Shuttle',
    category: 'COD',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=ZRxxKHbvfuY',
  },
  {
    id: 'ex-022',
    name: 'L-Drill',
    category: 'COD',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=yP9RQDLm8y4',
  },
  {
    id: 'ex-023',
    name: 'Pro Agility',
    category: 'COD',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=brFHyOtTwH4',
  },
  {
    id: 'ex-024',
    name: 'Cone Drills',
    category: 'COD',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=VNbZXU5fRfE',
  },
  {
    id: 'ex-025',
    name: 'W-Drill',
    category: 'COD',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=2y3OJ9PL5Go',
  },
  {
    id: 'ex-026',
    name: 'Box Drill',
    category: 'COD',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=6cGduTD_7Z4',
  },
  {
    id: 'ex-027',
    name: 'Zig-Zag Drill',
    category: 'COD',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=rLpC_mKdPuY',
  },

  // Plyometrics
  {
    id: 'ex-028',
    name: 'Box Jumps',
    category: 'Plyometrics',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=NBY9-kTuHEk',
  },
  {
    id: 'ex-029',
    name: 'Depth Jumps',
    category: 'Plyometrics',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=u9LN8TJMfQg',
  },
  {
    id: 'ex-030',
    name: 'Broad Jumps',
    category: 'Plyometrics',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=BKJKDwiJPCQ',
  },
  {
    id: 'ex-031',
    name: 'Hurdle Hops',
    category: 'Plyometrics',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=1tDqxWfRXrc',
  },
  {
    id: 'ex-032',
    name: 'Single-Leg Bounds',
    category: 'Plyometrics',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['RB', 'WR', 'DB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=R3DGOSh-fHI',
  },
  {
    id: 'ex-033',
    name: 'Tuck Jumps',
    category: 'Plyometrics',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=Sbkv9JkZvAE',
  },
  {
    id: 'ex-034',
    name: 'Medicine Ball Slams',
    category: 'Plyometrics',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=TFDCh9VmU0A',
  },
  {
    id: 'ex-035',
    name: 'Clapping Push-ups',
    category: 'Plyometrics',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=mX7T0JqIOdA',
  },

  // Mobility
  {
    id: 'ex-036',
    name: 'Hip Flexor Stretch',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=YQmpO9VT2X4',
  },
  {
    id: 'ex-037',
    name: 'Hamstring Stretch',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=3B-3Khbht5s',
  },
  {
    id: 'ex-038',
    name: 'Thoracic Spine Rotation',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=1-Sb3vGry_w',
  },
  {
    id: 'ex-039',
    name: 'Ankle Mobility Drills',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=0-c3rHt0xCc',
  },
  {
    id: 'ex-040',
    name: 'Shoulder Dislocations',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=02HdChcpyBs',
  },
  {
    id: 'ex-041',
    name: 'Cat-Cow Stretch',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
  },
  {
    id: 'ex-042',
    name: 'World Greatest Stretch',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=T3a7yH8M3_8',
  },
  {
    id: 'ex-043',
    name: 'Couch Stretch',
    category: 'Mobility',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=x4YNi4lI1i0',
  },

  // Technique
  {
    id: 'ex-044',
    name: 'Form Running Drills',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=D-fmh70e1sU',
  },
  {
    id: 'ex-045',
    name: 'A-Skips',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=E7HXKXYTDzk',
  },
  {
    id: 'ex-046',
    name: 'B-Skips',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=6Q6BIrLj7VU',
  },
  {
    id: 'ex-047',
    name: 'High Knees',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=8opcQdC-V-U',
  },
  {
    id: 'ex-048',
    name: 'Butt Kicks',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=R_YCYEhx46I',
  },
  {
    id: 'ex-049',
    name: 'Karaoke',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=gj8dusAIkTs',
  },
  {
    id: 'ex-050',
    name: 'Backpedal Technique',
    category: 'Technique',
    intensity: 'low',
    isGlobal: true,
    positionTags: ['DB', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=XCl0c4LJvRk',
  },
  {
    id: 'ex-051',
    name: 'Pass Rush Moves',
    category: 'Technique',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['DL', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=K5kNc1AnJUk',
  },
  {
    id: 'ex-052',
    name: 'Route Running',
    category: 'Technique',
    intensity: 'mod',
    isGlobal: true,
    positionTags: ['WR', 'TE'],
    youtubeUrl: 'https://www.youtube.com/watch?v=v3d0FRjsv1w',
  },

  // Conditioning
  {
    id: 'ex-053',
    name: 'Gassers',
    category: 'Conditioning',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=kUPQs5kRiEY',
  },
  {
    id: 'ex-054',
    name: 'Stadium Stairs',
    category: 'Conditioning',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=RQdNqJlKC5U',
  },
  {
    id: 'ex-055',
    name: 'Bike Intervals',
    category: 'Conditioning',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=7HrSNKvp0h0',
  },
  {
    id: 'ex-056',
    name: 'Rowing Intervals',
    category: 'Conditioning',
    intensity: 'mod',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=MmQA_HexU0U',
  },
  {
    id: 'ex-057',
    name: 'Battle Ropes',
    category: 'Conditioning',
    intensity: 'high',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=u_MEHG0g0Mc',
  },
  {
    id: 'ex-058',
    name: 'Prowler Push',
    category: 'Conditioning',
    intensity: 'high',
    isGlobal: true,
    positionTags: ['OL', 'DL', 'LB'],
    youtubeUrl: 'https://www.youtube.com/watch?v=b3QwMLxKLJ0',
  },

  // Recovery
  {
    id: 'ex-059',
    name: 'Foam Rolling',
    category: 'Recovery',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=GHmDKREUaME',
  },
  {
    id: 'ex-060',
    name: 'Static Stretching',
    category: 'Recovery',
    intensity: 'low',
    isGlobal: true,
    youtubeUrl: 'https://www.youtube.com/watch?v=g_tea8ZNk5A',
  },
];

/**
 * Search catalog by name and category
 */
export function searchCatalog(
  query: string,
  category?: string,
  position?: Position
): Exercise[] {
  const lowerQuery = query.toLowerCase().trim();

  return globalCatalog.filter((exercise) => {
    const matchesQuery = !lowerQuery || exercise.name.toLowerCase().includes(lowerQuery);
    const matchesCategory = !category || exercise.category === category;
    const matchesPosition = !position || !exercise.positionTags || exercise.positionTags.includes(position);

    return matchesQuery && matchesCategory && matchesPosition;
  });
}
